apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-one-deploy
  namespace: apidoc-aggregator
  labels:
    app: microservice-one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-one
  template:
    metadata:
      labels:
        app: microservice-one
    spec:
      containers:
      - name: microservice-one
        image: feet312/microservice-one  # on server
        # image: microserviceone
        ports: 
        - name: http
          containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: microservice-one-service
  namespace: apidoc-aggregator
spec:
  # type: NodePort
  selector:
    app: microservice-one
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
      # nodePort: 32180
---
